scoreboard:
  title: "&b&lFrozed Club &3[Dev]"
  normal:
    - "&7&m--------------------"
    - "&bOnline:"
    - "%players%"
    - ""
    - "&bRank:"
    - "%rank%"
    - ""
    - "&bdev.frozed.club"
    - "&7&m--------------------"

queues:
  - "FrozedSG"
  - "FrozedSumo"
  - "FrozedTeams"
  - "FrozedMeetup"
  - "FrozedUHCRun"
  - "ZenPractice"